
# Project ID - Keep this the first line!
project_id = "phzcazcyjhlmdchcjagy"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[realtime]
enabled = true

[studio]
enabled = true
port = 54323

# Enable pg_cron extension
[db.extensions]
pg_cron = true

[functions.create-checkout]
verify_jwt = true

[functions.check-subscription]
verify_jwt = true

[functions.customer-portal]
verify_jwt = true

[functions.generate-flashcards]
verify_jwt = true
